uploads = []
generated = []

[[outputs]]
id = "ntt4B84e6-Ef96qmrwGyn"
uri = "file://FoodScope_Project_Document.zip"
type = "unspecified"
title = "FoodScope Project Document (HTML + Screenshots)"

[[outputs]]
id = "lWpumbXX97KYuuXWeEFHt"
uri = "file://FoodScope_Project_Document.docx"
type = "word_document"
title = "FoodScope Project Document (.docx)"
